### ISSUE TITLE
Config retry_limit does not work.

### ISSUE THREAD

**Issue by JeremyVriens** [python-gino/gino-aiohttp#5]
## Expected Behavior

When specifying a retry_limit (as seen in the code https://github.com/python-gino/gino-aiohttp/blob/master/src/gino_aiohttp.py#L152), I'm expecting the code to exit after x retries.

## Actual Behavior

The amount of retries is never incremented, thus the retries will always stay at 0, meaning it'll never get out of the "trying to connect" loop.

## Steps to Reproduce the Problem

  1.  Use the following config:
```
app["config"] = {
    "gino": {
        "dsn": "postgres://username:password@example.com:5432/db",
        "retry_limit": 3,
    },
```
  2.  Run the common usage
  3. Expected result; raise an exception after 3 connection retries

## Specifications

* Python version: 3.8
* GINO version: 1.0.0
* gino-aiohttp version: 0.1.0
* aiohttp version: 3.6.2

**Comment by norlyakov** [comment]
Same issue - **_retries_** variable is simply not incrementing in the code.

**Comment by norlyakov** [comment]
Made PR:
https://github.com/python-gino/gino-aiohttp/pull/6

**Comment by fantix** [comment]
Thanks for the report and the PR! Closing as #6 is merged.
